import {ARSENAL_BY_ID,familyPower} from './arsenal.js';
import {mv,mvFor} from './arsenal-metrics.js';
import {srand} from './run-rng.js';
// Cooldowns are read before profile() runs, so they go through the raw state.
const M=(id,key,p)=>mvFor(p,id,key,state(p,id));
const TAU=Math.PI*2;
const rt=(p,id)=>p._arsenalRt||(p._arsenalRt={}), key=>{};
const state=(p,id)=>p.arsenal?.[id]||{tier:0,branch:null,evo:0};
const lvl=(p,id)=>familyPower(state(p,id));
const ready=(p,id,dt,base)=>{const r=p._arsenalRt||(p._arsenalRt={});r[id]=(r[id]??srand()*base)-dt;if(r[id]<=0){r[id]=base;return true}return false};
const nearest=(enemies,x,y)=>{let b=null,d=Infinity;for(const e of enemies){if(e.dead)continue;const dd=(e.x-x)**2+(e.y-y)**2;if(dd<d){d=dd;b=e}}return b};
const strongest=enemies=>[...enemies].filter(e=>!e.dead).sort((a,b)=>(b.hp||0)-(a.hp||0))[0];
const shot=(shots,x,y,a,speed,damage,kind='arsenal',extra={})=>shots.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:extra.r||3,life:extra.life||1.5,damage,kind,pierce:extra.pierce||0,ricochet:extra.ricochet||0,target:extra.target,turn:extra.turn||0});
const area=(enemies,x,y,r,damage,hit)=>{const r2=r*r;for(const e of enemies)if(!e.dead&&(e.x-x)**2+(e.y-y)**2<r2)hit(e,damage)};
const fx=(p,type,data)=>{(p.arsenalFx||(p.arsenalFx=[])).push({type,life:data.life||.3,max:data.life||.3,...data})};
function profile(p,id){const s=state(p,id),f=ARSENAL_BY_ID[id],power=Math.max(1,familyPower(s)),branch=s.branch,e=s.evo||0;return{s,f,power,branch,e,mult:1+power*.13+(branch?e*.18:0)}}
// `controlResist` is a generic per-enemy dial, not a boss import: a sector
// commander sets its own from its doctrine, and everything else leaves it
// undefined and gets pushed in full. It is capped so control always works.
export function tickArsenal(p,dt,c){
 // Shadow the bare read with the player-aware one: every mv() below now
 // carries this frame's Alignment modifiers without 30 separate edits.
 const mv=(id,key,st)=>mvFor(p,id,key,st);
const {enemies,shots,enemyShots,damageEnemy,elapsed}=c;const cfg=p.configurations||new Set();
 const has=id=>(state(p,id).tier||0)>0;
 // Kinetic families
 if(has('rail')&&ready(p,'rail',dt,M('rail','cooldown',p))){const q=profile(p,'rail'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x),n=mv('rail','shots',q.s);for(let i=0;i<n;i++)shot(shots,p.x,p.y,a+(i-(n-1)/2)*.07,900,mv('rail','damage',q.s),'rail',{pierce:mv('rail','pierce',q.s)+(cfg.has('gravity-spear')?2:0),r:q.branch==='a'?5:3});fx(p,'line',{x:p.x,y:p.y,a,len:220,life:.12})}}
 if(has('repeater')&&ready(p,'repeater',dt,M('repeater','cooldown',p))){const q=profile(p,'repeater'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x),n=mv('repeater','shots',q.s);for(let i=0;i<n;i++)shot(shots,p.x,p.y,a+(srand()-.5)*.06,700,mv('repeater','damage',q.s),'repeater',{r:q.branch==='b'?5:2,ricochet:cfg.has('ballistic-cyclone')?1:0})}}
 if(has('scatter')&&ready(p,'scatter',dt,M('scatter','cooldown',p))){const q=profile(p,'scatter'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x),n=mv('scatter','pellets',q.s),spread=mv('scatter','spread',q.s);for(let i=0;i<n;i++)shot(shots,p.x,p.y,a+(i-(n-1)/2)*spread/Math.max(1,n-1),620,mv('scatter','damage',q.s),'scatter',{pierce:q.branch==='b'?1+q.e:0})}}
 if(has('ricochet')&&ready(p,'ricochet',dt,M('ricochet','cooldown',p))){const q=profile(p,'ricochet'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x);shot(shots,p.x,p.y,a,580,mv('ricochet','damage',q.s),'ricochet',{ricochet:mv('ricochet','bounces',q.s),r:q.branch==='b'?7:3})}}
 if(has('hunter')&&ready(p,'hunter',dt,M('hunter','cooldown',p))){const q=profile(p,'hunter'),target=q.branch==='b'?strongest(enemies):nearest(enemies,p.x,p.y);if(target){const n=mv('hunter','shots',q.s);for(let i=0;i<n;i++)shot(shots,p.x,p.y,-Math.PI/2+(i-(n-1)/2)*.1,260,mv('hunter','damage',q.s),'hunter',{target,turn:4.5,r:4,life:3})}}
 // Energy
 if(has('beam')&&ready(p,'beam',dt,M('beam','cooldown',p))){const q=profile(p,'beam'),e=nearest(enemies,p.x,p.y);if(e){damageEnemy(e,mv('beam','damage',q.s));fx(p,'beam',{x:p.x,y:p.y,x2:e.x,y2:e.y,w:q.branch==='a'?8:2,life:.16});if(q.branch==='b')for(const e2 of enemies.filter(x=>x!==e).slice(0,q.e+1))damageEnemy(e2,8*q.mult)}}
 if(has('sweep')&&ready(p,'sweep',dt,M('sweep','cooldown',p))){const q=profile(p,'sweep'),r=mv('sweep','radius',q.s);area(enemies,p.x,p.y,r,mv('sweep','damage',q.s),damageEnemy);fx(p,'ring',{x:p.x,y:p.y,r,life:.3});if(q.branch==='b')fx(p,'ring',{x:p.x,y:p.y,r:r*.72,life:.3})}
 if(has('prism')&&ready(p,'prism',dt,M('prism','cooldown',p))){const q=profile(p,'prism'),targets=[...enemies].filter(e=>!e.dead).sort((a,b)=>((a.x-p.x)**2+(a.y-p.y)**2)-((b.x-p.x)**2+(b.y-p.y)**2)).slice(0,mv('prism','targets',q.s));for(const e of targets){damageEnemy(e,mv('prism','damage',q.s));fx(p,'beam',{x:p.x,y:p.y,x2:e.x,y2:e.y,w:1,life:.12})}}
 if(has('nova')&&ready(p,'nova',dt,M('nova','cooldown',p))){const q=profile(p,'nova'),r=mv('nova','radius',q.s);area(enemies,p.x,p.y,r,mv('nova','damage',q.s),damageEnemy);fx(p,'ring',{x:p.x,y:p.y,r,life:.35})}
 if(has('arc')&&ready(p,'arc',dt,M('arc','cooldown',p))){const q=profile(p,'arc'),targets=[...enemies].filter(e=>!e.dead).slice(0,mv('arc','targets',q.s));let x=p.x,y=p.y;for(const e of targets){damageEnemy(e,mv('arc','damage',q.s));fx(p,'beam',{x,y,x2:e.x,y2:e.y,w:2,life:.11});x=e.x;y=e.y}}
 // Melee + explosive
 if(has('orbit')){const q=profile(p,'orbit'),r=mv('orbit','radius',q.s),n=mv('orbit','blades',q.s);for(const e of enemies)if(!e.dead){const d=Math.hypot(e.x-p.x,e.y-p.y);if(Math.abs(d-r)<12+(q.branch==='b'?12:0))damageEnemy(e,mv('orbit','dps',q.s)*dt)}if(ready(p,'orbitFx',dt,.18))for(let i=0;i<n;i++){const a=elapsed*2.4+i*TAU/n;fx(p,'dot',{x:p.x+Math.cos(a)*r,y:p.y+Math.sin(a)*r,r:q.branch==='b'?8:4,life:.2})}}
 if(has('launchblade')&&ready(p,'launchblade',dt,M('launchblade','cooldown',p))){const q=profile(p,'launchblade'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x),n=q.power>5?2:1;for(let i=0;i<n;i++)shot(shots,p.x,p.y,a+(i?Math.PI*.08:0),500,mv('launchblade','damage',q.s),'blade',{pierce:mv('launchblade','pierce',q.s),r:6,life:2})}}
 if(has('slash')&&ready(p,'slash',dt,M('slash','cooldown',p))){const q=profile(p,'slash'),e=nearest(enemies,p.x,p.y);if(e){const a=Math.atan2(e.y-p.y,e.x-p.x),range=mv('slash','range',q.s);for(const t of enemies)if(!t.dead){const da=Math.atan2(t.y-p.y,t.x-p.x),d=Math.hypot(t.x-p.x,t.y-p.y);if(d<range&&Math.abs(Math.atan2(Math.sin(da-a),Math.cos(da-a)))<mv('slash','arc',q.s))damageEnemy(t,mv('slash','damage',q.s))}fx(p,'arc',{x:p.x,y:p.y,a,r:range,life:.18})}}
 if(has('drill')&&ready(p,'drill',dt,M('drill','cooldown',p))){const q=profile(p,'drill'),e=q.branch==='a'?strongest(enemies):nearest(enemies,p.x,p.y);if(e){damageEnemy(e,mv('drill','damage',q.s));fx(p,'beam',{x:p.x,y:p.y,x2:e.x,y2:e.y,w:5,life:.2})}}
 if(has('ram')&&p.dashTime>0){const q=profile(p,'ram');for(const e of enemies)if(!e.dead&&!e._arsenalRam&&Math.hypot(e.x-p.x,e.y-p.y)<e.r+p.r+18){e._arsenalRam=true;damageEnemy(e,mv('ram','damage',q.s))}if(q.branch==='b'&&ready(p,'phantom',dt,.12))fx(p,'dot',{x:p.x-p.dashDir.x*34,y:p.y-p.dashDir.y*34,r:10,life:.35})}else for(const e of enemies)e._arsenalRam=false;
 if(has('missile')&&ready(p,'missile2',dt,M('missile','cooldown',p))){const q=profile(p,'missile'),target=nearest(enemies,p.x,p.y);if(target){const n=mv('missile','shots',q.s);for(let i=0;i<n;i++)shot(shots,p.x,p.y,-Math.PI/2+(i-(n-1)/2)*.08,220,mv('missile','damage',q.s),'missile',{target,turn:4,r:q.branch==='b'?7:4,life:3})}}
 if(has('mortar')&&ready(p,'mortar',dt,M('mortar','cooldown',p))){const q=profile(p,'mortar'),e=nearest(enemies,p.x,p.y);if(e){const r=mv('mortar','radius',q.s);area(enemies,e.x,e.y,r,mv('mortar','damage',q.s),damageEnemy);fx(p,'ring',{x:e.x,y:e.y,r,life:.35})}}
 if(has('cluster')&&ready(p,'cluster',dt,M('cluster','cooldown',p))){const q=profile(p,'cluster'),e=nearest(enemies,p.x,p.y);if(e){const n=mv('cluster','bomblets',q.s),a0=Math.atan2(e.y-p.y,e.x-p.x);for(let i=0;i<n;i++)shot(shots,p.x,p.y,a0+(i-(n-1)/2)*.18,420,mv('cluster','damage',q.s),'cluster',{pierce:state(p,'cluster').tier>=4?1:0})}}
 if(has('mine')&&ready(p,'mine2',dt,M('mine','cooldown',p))){const q=profile(p,'mine'),n=mv('mine','mines',q.s);for(let i=0;i<n;i++)shots.push({x:p.x+(srand()-.5)*28,y:p.y+(srand()-.5)*28,vx:0,vy:0,r:q.branch==='b'?12:8,life:7,damage:mv('mine','damage',q.s),kind:'mine',pierce:0})}
 if(has('plasma')&&ready(p,'plasma',dt,M('plasma','cooldown',p))){const q=profile(p,'plasma'),e=nearest(enemies,p.x,p.y);if(e){const r=mv('plasma','radius',q.s);area(enemies,e.x,e.y,r,mv('plasma','damage',q.s),damageEnemy);fx(p,'zone',{x:e.x,y:e.y,r,life:mv('plasma','duration',q.s)})}}
 // Autonomous, defense, control
 if(has('drone')&&ready(p,'drone2',dt,M('drone','cooldown',p))){const q=profile(p,'drone'),e=nearest(enemies,p.x,p.y);if(e){const n=mv('drone','units',q.s);for(let i=0;i<n;i++){const a=i*TAU/n+elapsed;shot(shots,p.x+Math.cos(a)*60,p.y+Math.sin(a)*60,Math.atan2(e.y-p.y,e.x-p.x),560,mv('drone','damage',q.s),'drone')}}}
 if(has('funnels')&&ready(p,'funnels',dt,M('funnels','cooldown',p))){const q=profile(p,'funnels'),n=mv('funnels','units',q.s);for(let i=0;i<n;i++){const e=enemies[(i*3)%Math.max(1,enemies.length)];if(e&&!e.dead){const a=i*TAU/n+elapsed*.8,x=p.x+Math.cos(a)*95,y=p.y+Math.sin(a)*95;shot(shots,x,y,Math.atan2(e.y-y,e.x-x),600,mv('funnels','damage',q.s),'funnel')}}}
 if(has('sentry')&&ready(p,'sentry',dt,M('sentry','cooldown',p))){const q=profile(p,'sentry'),e=nearest(enemies,p.x,p.y);if(e){const n=mv('sentry','units',q.s);for(let i=0;i<n;i++)shot(shots,p.x+(i-(n-1)/2)*24,p.y+42,Math.atan2(e.y-p.y-42,e.x-p.x),520,mv('sentry','damage',q.s),'sentry')}}
 if(has('interceptor')){const q=profile(p,'interceptor'),r=mv('interceptor','radius',q.s);for(const s of enemyShots)if(!s.dead&&Math.hypot(s.x-p.x,s.y-p.y)<r){s.dead=true;if(q.branch==='b'){const e=nearest(enemies,s.x,s.y);if(e)shot(shots,s.x,s.y,Math.atan2(e.y-s.y,e.x-s.x),520,mv('interceptor','damage',q.s),'counter')}break}}
 if(has('barrier')){const q=profile(p,'barrier'),r=mv('barrier','radius',q.s);for(const e of enemies)if(!e.dead&&Math.hypot(e.x-p.x,e.y-p.y)<r)damageEnemy(e,mv('barrier','dps',q.s)*dt);if(ready(p,'barrierFx',dt,.2))fx(p,'ring',{x:p.x,y:p.y,r,life:.22})}
 if(has('graviton')&&ready(p,'graviton',dt,.06)){const q=profile(p,'graviton'),r=mv('graviton','radius',q.s);for(const e of enemies)if(!e.dead){const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d<r){const force=(mv('graviton','force',q.s))*(1-(e.controlResist||0));e.x+=dx/d*force*dt;e.y+=dy/d*force*dt;if(d<35)damageEnemy(e,mv('graviton','dps',q.s)*dt)}}}
 if(has('repulsor')&&ready(p,'repulsor',dt,M('repulsor','cooldown',p))){const q=profile(p,'repulsor'),r=mv('repulsor','radius',q.s);for(const e of enemies)if(!e.dead){const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy)||1;if(d<r){const f=(mv('repulsor','force',q.s))*(1-(e.controlResist||0));e.x+=dx/d*f;e.y+=dy/d*f;damageEnemy(e,mv('repulsor','damage',q.s))}}fx(p,'ring',{x:p.x,y:p.y,r,life:.3})}
 if(has('mark')&&ready(p,'mark',dt,M('mark','cooldown',p))){for(const e of enemies)e._execMark=false;const q=profile(p,'mark'),targets=[...enemies].filter(e=>!e.dead).sort((a,b)=>(b.hp||0)-(a.hp||0)).slice(0,mv('mark','targets',q.s));for(const e of targets){e._execMark=true;e._execMarkMult=mv('mark','markMult',q.s);fx(p,'ring',{x:e.x,y:e.y,r:e.r+10,life:.45})}}
 // Exotic: infer kills since previous tick.
 const prev=p._arsenalKills??p.kills,delta=Math.max(0,p.kills-prev);p._arsenalKills=p.kills;if(delta>0&&has('death')){const q=profile(p,'death'),n=Math.min(6,delta+(q.branch? q.e:0));for(let i=0;i<n;i++){const e=enemies[i%Math.max(1,enemies.length)];if(e&&!e.dead){if(q.branch==='b')shot(shots,p.x,p.y,Math.atan2(e.y-p.y,e.x-p.x),520,mv('death','damage',q.s),'soul',{target:e,turn:3.5});else{area(enemies,e.x,e.y,mv('death','radius',q.s),mv('death','damage',q.s),damageEnemy);fx(p,'ring',{x:e.x,y:e.y,r:mv('death','radius',q.s),life:.25})}}}}
 if(has('temporal')&&ready(p,'temporal',dt,M('temporal','cooldown',p))){const q=profile(p,'temporal'),targets=[...enemies].filter(e=>!e.dead).slice(0,mv('temporal','targets',q.s));for(const e of targets){damageEnemy(e,mv('temporal','damage',q.s));fx(p,'beam',{x:p.x,y:p.y,x2:e.x,y2:e.y,w:2,life:.4})}if(cfg.has('aftershock')&&has('nova')){const r=90+lvl(p,'nova')*10;area(enemies,p.x,p.y,r,10*q.mult,damageEnemy);fx(p,'ring',{x:p.x,y:p.y,r,life:.4})}}
 // Selected cross-system hooks.
 if(cfg.has('seraph-wing')&&ready(p,'cfg-seraph',dt,1.1)){const e=nearest(enemies,p.x,p.y);if(e)for(let i=0;i<2;i++)shot(shots,p.x,p.y,-Math.PI/2+i*.12,240,10,'missile',{target:e,turn:4,life:3})}
 if(cfg.has('mine-drive')&&p.dashTime>0&&ready(p,'cfg-mine',dt,.12))shots.push({x:p.x,y:p.y,vx:0,vy:0,r:8,life:5,damage:20,kind:'mine',pierce:0});
 if(cfg.has('extinction-chain')&&delta>0&&enemies[0])for(const e of enemies.slice(0,Math.min(4,delta+2)))if(!e.dead)damageEnemy(e,7+delta*2);
}
export function applyMarkedDamage(e,d){return d*(e?._execMarkMult||1)}
export function updateArsenalFx(p,dt){for(const f of p.arsenalFx||[])f.life-=dt;p.arsenalFx=(p.arsenalFx||[]).filter(f=>f.life>0)}
export function drawArsenalFx(ctx,p,palette){for(const f of p.arsenalFx||[]){ctx.save();ctx.globalAlpha=Math.max(0,f.life/f.max);ctx.strokeStyle=palette.cyan;ctx.fillStyle='rgba(22,143,255,.12)';ctx.shadowColor=palette.cyan;ctx.shadowBlur=10;if(f.type==='beam'||f.type==='line'){ctx.lineWidth=f.w||2;ctx.beginPath();ctx.moveTo(f.x,f.y);if(f.x2!=null)ctx.lineTo(f.x2,f.y2);else ctx.lineTo(f.x+Math.cos(f.a||0)*(f.len||140),f.y+Math.sin(f.a||0)*(f.len||140));ctx.stroke()}else if(f.type==='ring'||f.type==='zone'){ctx.beginPath();ctx.arc(f.x,f.y,f.r||30,0,TAU);f.type==='zone'?ctx.fill():ctx.stroke()}else if(f.type==='arc'){ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,f.r||80,(f.a||0)-.65,(f.a||0)+.65);ctx.stroke()}else{ctx.beginPath();ctx.arc(f.x,f.y,f.r||4,0,TAU);ctx.fill()}ctx.restore()}}
