import {generateRunSalvage,salvageDismantleValue,salvageSummary} from './rewards.js';
import {SALVAGE_FAMILIES} from './sector-content.js';
import {CONFIGURATIONS,CONFIG_BY_ID} from './configurations.js';
import {CHALLENGE_CONTRACTS,ENDGAME_TIERS,sectorMastery,completedContracts,unlockedCircuit,arsenalArchive} from './endgame.js';
const $=s=>document.querySelector(s),KEY='mech-survivor-retention-v2';
const defaults={reliquary:0,salvage:[],equipped:{},discoveredConfigurations:[],prototypes:[],sectorMastery:[0,0,0,0,0],completedContracts:[],campaignClears:0,totalMastery:0,arsenalArchive:[]};
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('mech-survivor-retention-v1')||'{}');return{...structuredClone(defaults),...raw,salvage:Array.isArray(raw.salvage)?raw.salvage:[],equipped:raw.equipped||{},discoveredConfigurations:Array.isArray(raw.discoveredConfigurations)?raw.discoveredConfigurations:[],prototypes:Array.isArray(raw.prototypes)?raw.prototypes:[],sectorMastery:Array.isArray(raw.sectorMastery)?raw.sectorMastery:[0,0,0,0,0],completedContracts:Array.isArray(raw.completedContracts)?raw.completedContracts:[],arsenalArchive:Array.isArray(raw.arsenalArchive)?raw.arsenalArchive:[]}}catch{return structuredClone(defaults)}}
let save=load(),pending=[];
function persist(){localStorage.setItem(KEY,JSON.stringify(save));localStorage.setItem('mech-survivor-retention-v1',JSON.stringify(save));renderCounts()}
function screen(id){document.querySelectorAll('.screen').forEach(e=>e.classList.add('hidden'));$(id)?.classList.remove('hidden');queueMicrotask(()=>document.querySelector(id+' button:not([disabled])')?.focus())}
function renderCounts(){if($('#garage-count'))$('#garage-count').textContent=save.salvage.length;if($('#reliquary-count'))$('#reliquary-count').textContent=save.reliquary||0;if($('#config-count'))$('#config-count').textContent=save.discoveredConfigurations.length+'/'+CONFIGURATIONS.length}
function isEquipped(item){return save.equipped[item.slot]===item.id}
function family(item){return SALVAGE_FAMILIES.find(f=>f.id===item.familyKey)}
function calibrationCost(item){return Math.max(2,(item.tier||1)*3+((item.calibration||0)*4))}
function learnFromItem(item){if(item.source?.boss&&!save.prototypes.includes(item.familyKey))save.prototypes.push(item.familyKey)}
function learnFromSummary(summary){for(const id of summary.configurations||[])if(!save.discoveredConfigurations.includes(id))save.discoveredConfigurations.push(id);for(const [id,state] of Object.entries(summary.arsenal||{}))if((state?.tier||0)>0&&!save.arsenalArchive.includes(id))save.arsenalArchive.push(id)}
function recordMastery(summary,won){summary.won=won;const w=Math.max(0,Math.min(4,summary.world||0)),m=sectorMastery(summary);save.sectorMastery[w]=Math.max(save.sectorMastery[w]||0,m);save.totalMastery=save.sectorMastery.reduce((a,b)=>a+b,0);for(const id of completedContracts(summary))if(!save.completedContracts.includes(id)){save.completedContracts.push(id);save.reliquary+=6}if(won&&w===4)save.campaignClears=(save.campaignClears||0)+1}
function ensureUI(){
 if(!$('#garage-open')){const b=document.createElement('button');b.id='garage-open';b.innerHTML='GARAGE <b id="garage-count">0</b>';const stack=$('#title .menu-stack');stack?.insertBefore(b,$('#settings-open'));b.onclick=()=>{renderGarage();screen('#garage')}}
 if(!$('#garage')){const g=document.createElement('section');g.id='garage';g.className='screen hidden panel-screen garage-screen';g.innerHTML='<div class="kicker">FRAME PREPARATION // PERSISTENT SALVAGE</div><h2>GARAGE</h2><div class="currency">RELIQUARY ◇ <b id="reliquary-count">0</b> · CONFIGS <b id="config-count">0/36</b></div><div class="garage-tabs"><button id="garage-salvage-tab">SALVAGE</button><button id="garage-config-tab">CONFIGURATIONS</button><button id="garage-mastery-tab">MASTERY</button></div><div class="garage-layout"><div id="garage-grid" class="shop-grid"></div><aside id="garage-inspector" class="genome-inspector"><h3>PREP BAY</h3><p>Equip one recovered component per slot. Boss relics can seed compatible weapon systems into the next sortie.</p></aside></div><button id="garage-back">‹ BACK</button>';document.body.append(g);$('#garage-back').onclick=()=>{screen('#title');window.mechGame?.stop()};$('#garage-salvage-tab').onclick=renderGarage;$('#garage-config-tab').onclick=renderConfigurations;$('#garage-mastery-tab').onclick=renderMastery}
 if(!$('#reward-reveal')){const r=document.createElement('section');r.id='reward-reveal';r.className='screen hidden reward-screen';r.innerHTML='<div class="kicker">RECOVERY CEREMONY</div><h2>SALVAGE SECURED</h2><p id="reward-runline"></p><div id="reward-items" class="reward-items"></div><button id="reward-continue">CONTINUE</button>';document.body.append(r)}
 if(!$('#retention-style')){const st=document.createElement('style');st.id='retention-style';st.textContent='.garage-layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:18px;width:min(1160px,94vw);margin:18px auto}.garage-tabs{display:flex;gap:8px;justify-content:center}.reward-items{display:flex;gap:14px;justify-content:center;flex-wrap:wrap;margin:24px}.reward-item{min-width:230px;padding:18px;border:1px solid rgba(120,231,255,.35);background:rgba(4,13,26,.94)}.reward-item.rare{border-color:#168fff}.reward-item.epic{border-color:#df55ff}.reward-item.mythic{border-color:#d6ae52;box-shadow:0 0 25px rgba(214,174,82,.18)}.garage-item.locked{outline:1px solid #d6ae52}.garage-item.equipped{box-shadow:0 0 0 2px #78e7ff inset}.garage-inspector-actions{display:flex;gap:8px;flex-wrap:wrap}.config-card.known,.mastery-card.complete{border-color:rgba(214,174,82,.6)}.mastery-meter{height:5px;background:#12243b;margin-top:10px}.mastery-meter b{display:block;height:100%;background:#78e7ff}@media(max-width:760px){.garage-layout{grid-template-columns:1fr}.garage-layout aside{order:-1}}';document.head.append(st)}renderCounts()}
function renderGarage(){ensureUI();const grid=$('#garage-grid');grid.innerHTML='';const items=[...save.salvage].sort((a,b)=>(b.acquiredAt||0)-(a.acquiredAt||0));if(!items.length)grid.innerHTML='<article class="shop-card"><div class="tier">EMPTY BAY</div><h3>NO SALVAGE RECOVERED</h3><p>Complete a sortie to recover your first persistent component.</p></article>';for(const item of items){const card=document.createElement('article');card.className='shop-card garage-item '+item.rarity+(item.locked?' locked':'')+(isEquipped(item)?' equipped':'');const fam=family(item);card.innerHTML='<div class="tier">'+item.rarityLabel+' · T'+item.tier+(isEquipped(item)?' · EQUIPPED':'')+'</div><h3>'+(item.familyName||fam?.name||item.slotLabel)+'</h3><p>'+item.slotLabel+' · '+item.affixes.map(a=>a.label+' +'+a.roll).join(' · ')+'</p><button>INSPECT</button>';card.querySelector('button').onclick=()=>inspect(item.id);grid.append(card)}renderCounts()}
function inspect(id){const item=save.salvage.find(x=>x.id===id);if(!item)return;const panel=$('#garage-inspector'),value=salvageDismantleValue(item),cost=calibrationCost(item),fam=family(item),eq=isEquipped(item),cal=item.calibration||0;panel.innerHTML='<div class="tier">'+item.rarityLabel+' // T'+item.tier+' // CAL '+cal+'/3</div><h3>'+(item.familyName||fam?.name||item.slotLabel)+'</h3><p>'+item.slotLabel+'</p><p>FAMILY TAGS // '+(item.familyTags||fam?.tags||[]).join(' · ').toUpperCase()+'</p><ul>'+item.affixes.map(a=>'<li>'+a.label+': +'+Math.round(a.roll*(1+cal*.1))+'</li>').join('')+'</ul><p>SOURCE // SECTOR 0'+((item.source?.world||0)+1)+(item.source?.boss?' · BOSS RELIC':'')+'</p><div class="garage-inspector-actions"><button id="garage-equip">'+(eq?'UNEQUIP':'EQUIP')+'</button><button id="garage-calibrate" '+(cal>=3||save.reliquary<cost?'disabled':'')+'>CALIBRATE · ◇ '+cost+'</button><button id="garage-lock">'+(item.locked?'UNLOCK':'LOCK')+'</button><button id="garage-dismantle" '+(item.locked||eq?'disabled':'')+'>DISMANTLE · ◇ '+value+'</button></div>';$('#garage-equip').onclick=()=>{if(eq)delete save.equipped[item.slot];else save.equipped[item.slot]=item.id;persist();renderGarage();inspect(id)};$('#garage-calibrate').onclick=()=>{if(cal>=3||save.reliquary<cost)return;save.reliquary-=cost;item.calibration=cal+1;persist();renderGarage();inspect(id)};$('#garage-lock').onclick=()=>{item.locked=!item.locked;persist();renderGarage();inspect(id)};$('#garage-dismantle').onclick=()=>{if(item.locked||eq)return;save.reliquary=(save.reliquary||0)+value;save.salvage=save.salvage.filter(x=>x.id!==id);persist();renderGarage();panel.innerHTML='<h3>DISMANTLED</h3><p>Reliquary material recovered.</p>'}}
function renderConfigurations(){ensureUI();const grid=$('#garage-grid');grid.innerHTML='';for(const c of CONFIGURATIONS){const known=save.discoveredConfigurations.includes(c.id),card=document.createElement('article');card.className='shop-card config-card '+(known?'known':'');card.innerHTML='<div class="tier">'+c.tier.toUpperCase()+' · '+(known?'IDENTIFIED':'UNKNOWN')+'</div><h3>'+(known?c.name:'???')+'</h3><p>'+(known?c.desc:'Achieve this machine identity during a sortie to archive it.')+'</p><small>'+(known?'REQUIRES // '+c.requires.join(' + ').toUpperCase():'SIGNATURE ENCRYPTED')+'</small>';grid.append(card)}$('#garage-inspector').innerHTML='<h3>CONFIGURATION DATABASE</h3><p>'+save.discoveredConfigurations.length+' / '+CONFIGURATIONS.length+' machine identities identified.</p><p>Configurations are discoveries, not purchases. Build them in combat and they become part of your permanent archive.</p>';renderCounts()}
function renderMastery(){ensureUI();const grid=$('#garage-grid');grid.innerHTML='';save.sectorMastery.forEach((m,i)=>{const c=document.createElement('article');c.className='shop-card mastery-card '+(m>=10?'complete':'');c.innerHTML='<div class="tier">SECTOR 0'+(i+1)+' MASTERY</div><h3>'+m+' / 10</h3><p>Clear, complete opportunities, discover Configurations and survive corruption to raise mastery.</p><div class="mastery-meter"><b style="width:'+m*10+'%"></b></div>';grid.append(c)});for(const c of CHALLENGE_CONTRACTS){const done=save.completedContracts.includes(c.id),el=document.createElement('article');el.className='shop-card mastery-card '+(done?'complete':'');el.innerHTML='<div class="tier">CHALLENGE CONTRACT · '+(done?'COMPLETE':'OPEN')+'</div><h3>'+c.name+'</h3><p>'+c.desc+'</p><small>REWARD // '+c.reward+'</small>';grid.append(el)}const circuit=unlockedCircuit({...save,configs:save.discoveredConfigurations.length});$('#garage-inspector').innerHTML='<h3>SOVEREIGN CIRCUIT</h3><p>TOTAL MASTERY // '+save.totalMastery+' / 50</p><p>CAMPAIGN CLEARS // '+save.campaignClears+'</p><p>ARSENAL DISCOVERED // '+save.arsenalArchive.length+' / '+arsenalArchive().length+'</p><p>HIGHEST CIRCUIT // '+(circuit?.name||'LOCKED')+'</p><p>'+(circuit?.desc||'Clear the full five-sector campaign to open endgame circuits.')+'</p>';renderCounts()}
function reveal(summary,won,continueFn){ensureUI();learnFromSummary(summary);recordMastery(summary,won);pending=generateRunSalvage(summary,won,String(Date.now()));for(const item of pending)learnFromItem(item);save.salvage.push(...pending);persist();$('#reward-runline').textContent='SECTOR 0'+(summary.world+1)+' · LV '+summary.level+' · '+summary.kills+' KILLS'+(summary.primaryConfiguration?' · '+(CONFIG_BY_ID[summary.primaryConfiguration]?.name||'CONFIGURATION'): '')+' · MASTERY '+sectorMastery(summary)+'/10';$('#reward-items').innerHTML=pending.map(item=>'<article class="reward-item '+item.rarity+'"><div class="tier">SALVAGE // '+item.rarityLabel+'</div><h3>'+(item.familyName||item.slotLabel)+'</h3><p>'+salvageSummary(item)+'</p><small>'+item.affixes.map(a=>a.label+' +'+a.roll).join(' · ')+'</small></article>').join('');$('#reward-continue').onclick=continueFn;screen('#reward-reveal')}
function loadoutBonuses(){const out={damage:0,hp:0,area:0,regen:0,coins:0,startFamily:null,prototypeTags:[]};for(const id of Object.values(save.equipped)){const item=save.salvage.find(x=>x.id===id);if(!item)continue;const mult=1+(item.calibration||0)*.1;for(const a of item.affixes||[]){const v=a.roll*mult;if(a.stat==='damage')out.damage+=v/200;if(a.stat==='hp')out.hp+=v*.6;if(a.stat==='area')out.area+=v/240;if(a.stat==='regen')out.regen+=v/30;if(a.stat==='salvage')out.coins+=v/180}if(item.source?.boss&&!out.startFamily){const tags=item.familyTags||family(item)?.tags||[];out.startFamily=tags.find(t=>['rail','repeater','scatter','ricochet','hunter','beam','sweep','prism','nova','arc','orbit','launchblade','slash','drill','ram','missile','mortar','cluster','mine','plasma','drone','funnels','sentry','interceptor','barrier','graviton','repulsor','mark','death','temporal'].includes(t))||null}out.prototypeTags.push(...(item.familyTags||[]))}return out}
function resetRetention(){save=structuredClone(defaults);persist();renderGarage()}
function hookMeta(){if(!window.MechMeta?.endRun)return false;if(window.MechMeta.__retentionHooked)return true;const original=window.MechMeta.endRun.bind(window.MechMeta);window.MechMeta.endRun=(won,summary)=>reveal(summary,won,()=>original(won,summary));window.MechMeta.__retentionHooked=true;window.MechRetention={renderGarage,get salvage(){return save.salvage},get reliquary(){return save.reliquary},getLoadoutBonuses:loadoutBonuses,reset:resetRetention,get discoveredConfigurations(){return save.discoveredConfigurations},get prototypes(){return save.prototypes},get mastery(){return save.sectorMastery},get campaignClears(){return save.campaignClears}};return true}
function boot(){ensureUI();if(!hookMeta()){let tries=0;const id=setInterval(()=>{if(hookMeta()||++tries>50)clearInterval(id)},20)}}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();
